// GENERATED — DO NOT EDIT.
// Tork PII country registry, bundle version 1.2.0 (content cfd4f61ebaf4).
// Source: landing/lib/pii/registry/ via scripts/pii/generate-sdk-registry.ts.
// Regenerate:  npx tsx scripts/pii/generate-sdk-registry.ts
// See generated/sdk-registry/README.md for the rules this data is fed to.

package torkpii

const RegistryVersion = "1.2.0"
const ContentHash = "cfd4f61ebaf45e743ba20d995d5ed585dd284778a2b3202ba917d71164b4fa26"

// The keyword gate is ASYMMETRIC — see README.md, rule 3.
const KeywordWindowBefore = 60
const KeywordWindowAfter = 40
const ContextWindow = 60
const LabelWindow = 60
const LabelReach = 25

const NearMissRedaction = "[NATIONAL_ID_REDACTED]"
const NearMissType = "national_id_near_miss"

var NearMissKinds = []string{"health_id", "national_id", "tax_id"}

var TableDelimiters = []string{"\t", "|", ";", ","}
const TableMaxHeaderLength = 32
const TableMaxHeaderWords = 4
const TableMinRows = 3
const TableMinCommaColumns = 3

var Labels = []string{
	`AADHAAR`,
	`ABN`,
	`ACN`,
	`BVN`,
	`CA_PASSPORT`,
	`CA_PHONE`,
	`CA_POSTAL`,
	`CNIC`,
	`CNPJ`,
	`CODICE_FISCALE`,
	`CPF`,
	`EMIRATES_ID`,
	`GHANA_CARD`,
	`IFSC`,
	`ITIN`,
	`KRA_PIN`,
	`MEDICARE`,
	`MYKAD`,
	`MY_NUMBER`,
	`NATIONAL_ID`,
	`NHS`,
	`NIK`,
	`NIN`,
	`NINO`,
	`NRIC`,
	`PAN`,
	`PASSPORT`,
	`PHONE`,
	`PINCODE`,
	`PO_BOX`,
	`RESIDENT_ID`,
	`RFC`,
	`RRN`,
	`SIN`,
	`SORT_CODE`,
	`TAN`,
	`TAX_ID`,
	`TFN`,
	`UK_POSTCODE`,
	`ZA_ID`,
}

var ReferenceLabels = []string{
	`order`,
	`invoice`,
	`purchase order`,
	`po no`,
	`po number`,
	`job number`,
	`job no`,
	`booking`,
	`tracking`,
	`consignment`,
	`waybill`,
	`airway bill`,
	`awb`,
	`docket`,
	`quote`,
	`quotation`,
	`ticket`,
	`receipt`,
	`serial number`,
	`asset tag`,
	`part number`,
	`stock code`,
	`batch`,
	`shipment`,
	`dispatch note`,
	`delivery note`,
	`work order`,
	`contract number`,
	`policy number`,
	`meter number`,
	`case id`,
	`bestelling`,
	`bestelnommer`,
	`faktuur`,
	`kwotasie`,
	`commande`,
	`facture`,
	`devis`,
	`bon de livraison`,
	`expédition`,
	`expedition`,
	`pedido`,
	`fatura`,
	`factura`,
	`orçamento`,
	`orcamento`,
	`presupuesto`,
	`remito`,
	`pesanan`,
	`nombor pesanan`,
	`invois`,
	`sebut harga`,
	`penghantaran`,
	`resit`,
	`आदेश`,
	`क्रय आदेश`,
	`चालान`,
	`कोटेशन`,
	`रसीद`,
	`آرڈر`,
	`انوائس`,
	`رسید`,
	`کوٹیشن`,
	`ترسیل`,
	`طلب`,
	`أمر شراء`,
	`فاتورة`,
	`عرض سعر`,
	`إيصال`,
	`شحنة`,
	`بوليصة`,
	`注文`,
	`注文番号`,
	`発注`,
	`発注番号`,
	`請求書`,
	`請求番号`,
	`伝票`,
	`伝票番号`,
	`見積`,
	`見積番号`,
	`管理番号`,
	`在庫番号`,
	`受注`,
	`出荷`,
	`订单`,
	`訂單`,
	`订单编号`,
	`訂單編號`,
	`发票`,
	`發票`,
	`采购`,
	`採購`,
	`报价`,
	`報價`,
	`运单`,
	`運單`,
	`物料编号`,
	`物料編號`,
	`库存`,
	`庫存`,
	`주문`,
	`주문번호`,
	`구매주문`,
	`송장`,
	`견적`,
	`견적서`,
	`운송장`,
	`자재번호`,
	`재고번호`,
	`ใบสั่งซื้อ`,
	`เลขที่ใบสั่งซื้อ`,
	`ใบแจ้งหนี้`,
	`ใบเสนอราคา`,
	`ใบส่งของ`,
	`รหัสพัสดุ`,
	`ใบงาน`,
}

var GenericIDKeywords = []string{
	`national id`,
	`national identity`,
	`national identification`,
	`national number`,
	`national code`,
	`identity number`,
	`identification number`,
	`id number`,
	`citizen id`,
	`citizen number`,
	`resident id`,
	`resident number`,
	`civil id`,
	`civil number`,
	`civil registration`,
	`personal number`,
	`personal identity`,
	`personal code`,
	`personal id`,
	`tax identification`,
	`tax reference`,
	`taxpayer number`,
	`taxpayer id`,
}

var LocalIDKeywords = []string{
	`cedula`,
	`cédula`,
	`iqama`,
	`nadra`,
	`cnic`,
	`aadhaar`,
	`voen`,
	`vöen`,
	`егн`,
	`oib`,
	`cpr-nummer`,
	`cpr nummer`,
	`kennitala`,
	`personnummer`,
	`adoazonosito`,
	`adóazonosító`,
	`szemelyi azonosito`,
	`személyi azonosító`,
	`kimlik`,
	`рнокпп`,
	`nid number`,
	`sars income tax`,
}

type Country struct {
	Code        string
	Name        string
	CallingCode string
	Bloc        bool
	Patterns    []string
}

var Countries = []Country{
	{Code: `AU`, Name: `Australia`, CallingCode: `61`, Bloc: false, Patterns: []string{`au_tfn`, `au_abn`, `au_medicare`, `au_acn`, `au_phone_intl`}},
	{Code: `US`, Name: `United States`, CallingCode: `1`, Bloc: false, Patterns: []string{`us_itin`, `us_passport_alpha`}},
	{Code: `GB`, Name: `United Kingdom`, CallingCode: `44`, Bloc: false, Patterns: []string{`uk_phone_full`, `uk_sort_code`, `uk_nino`, `uk_nhs`, `uk_postcode`}},
	{Code: `EU`, Name: `European Union`, CallingCode: ``, Bloc: true, Patterns: []string{`de_tax_id`}},
	{Code: `AE`, Name: `United Arab Emirates`, CallingCode: `971`, Bloc: false, Patterns: []string{`emirates_id`, `uae_phone`, `uae_landline`, `po_box`}},
	{Code: `SA`, Name: `Saudi Arabia`, CallingCode: `966`, Bloc: false, Patterns: []string{`sa_national_id`, `sa_phone`}},
	{Code: `NG`, Name: `Nigeria`, CallingCode: `234`, Bloc: false, Patterns: []string{`ng_nin`, `ng_bvn`, `ng_phone`}},
	{Code: `IN`, Name: `India`, CallingCode: `91`, Bloc: false, Patterns: []string{`in_aadhaar`, `in_pan`, `in_phone`, `in_ifsc`, `in_pincode`}},
	{Code: `JP`, Name: `Japan`, CallingCode: `81`, Bloc: false, Patterns: []string{`jp_my_number`, `jp_phone_intl`, `jp_phone_national`}},
	{Code: `CN`, Name: `China`, CallingCode: `86`, Bloc: false, Patterns: []string{`cn_resident_id`, `cn_phone_intl`, `cn_phone_national`}},
	{Code: `KR`, Name: `South Korea`, CallingCode: `82`, Bloc: false, Patterns: []string{`kr_rrn`, `kr_phone_intl`, `kr_phone_national`}},
	{Code: `BR`, Name: `Brazil`, CallingCode: `55`, Bloc: false, Patterns: []string{`br_cpf`, `br_cnpj`}},
	{Code: `CA`, Name: `Canada`, CallingCode: `1`, Bloc: false, Patterns: []string{`ca_sin`, `ca_phone`, `ca_postal_code`, `ca_passport`}},
	{Code: `ZA`, Name: `South Africa`, CallingCode: `27`, Bloc: false, Patterns: []string{`za_id_number`, `za_phone`}},
	{Code: `GH`, Name: `Ghana`, CallingCode: `233`, Bloc: false, Patterns: []string{`gh_ghana_card`}},
	{Code: `IT`, Name: `Italy`, CallingCode: `39`, Bloc: false, Patterns: []string{`it_codice_fiscale`}},
	{Code: `KE`, Name: `Kenya`, CallingCode: `254`, Bloc: false, Patterns: []string{`ke_kra_pin`}},
	{Code: `MU`, Name: `Mauritius`, CallingCode: `230`, Bloc: false, Patterns: []string{`mu_tan`}},
	{Code: `MX`, Name: `Mexico`, CallingCode: `52`, Bloc: false, Patterns: []string{`mx_rfc`}},
	{Code: `MY`, Name: `Malaysia`, CallingCode: `60`, Bloc: false, Patterns: []string{`my_mykad`}},
	{Code: `PK`, Name: `Pakistan`, CallingCode: `92`, Bloc: false, Patterns: []string{`pk_cnic`}},
	{Code: `SG`, Name: `Singapore`, CallingCode: `65`, Bloc: false, Patterns: []string{`sg_nric`}},
	{Code: `TH`, Name: `Thailand`, CallingCode: `66`, Bloc: false, Patterns: []string{`th_national_id`}},
	{Code: `ID`, Name: `Indonesia`, CallingCode: `62`, Bloc: false, Patterns: []string{`id_nik`}},
}

type Pattern struct {
	Name              string
	Country           string
	Kind              string
	Regex             string
	Redaction         string
	Type              string
	Label             string
	RequiresKeyword   bool
	AlwaysOn          bool
	Keywords          []string
	WholeWordKeywords []string
	NearMissKeywords  []string
	NearMissFallback  bool
	Checksum          string
	ChecksumRequired  bool
}

// Patterns is RE2-safe: no lookaround, no backreferences, no named groups.
var Patterns = []Pattern{
	{
		Name: `au_tfn`,
		Country: `AU`,
		Kind: `tax_id`,
		Regex: `\b\d{3}[ \t]?\d{3}[ \t]?\d{3}\b`,
		Redaction: `[TFN_REDACTED]`,
		Type: `au_tfn`,
		Label: `TFN`,
		RequiresKeyword: true,
		AlwaysOn: true,
		Keywords: []string{`tfn`, `tax file`, `tax number`},
		WholeWordKeywords: []string{},
		NearMissKeywords: []string{},
		NearMissFallback: true,
		Checksum: `au_tfn`,
		ChecksumRequired: true,
	},
	{
		Name: `au_abn`,
		Country: `AU`,
		Kind: `company`,
		Regex: `\b\d{2}[ \t]?\d{3}[ \t]?\d{3}[ \t]?\d{3}\b`,
		Redaction: `[ABN_REDACTED]`,
		Type: `au_abn`,
		Label: `ABN`,
		RequiresKeyword: true,
		AlwaysOn: true,
		Keywords: []string{`abn`, `business number`, `australian business`},
		WholeWordKeywords: []string{},
		NearMissKeywords: []string{},
		NearMissFallback: false,
		Checksum: `au_abn`,
		ChecksumRequired: true,
	},
	{
		Name: `au_medicare`,
		Country: `AU`,
		Kind: `health_id`,
		Regex: `\b\d{4}[ \t]?\d{5}[ \t]?\d{1}\b`,
		Redaction: `[MEDICARE_REDACTED]`,
		Type: `au_medicare`,
		Label: `MEDICARE`,
		RequiresKeyword: true,
		AlwaysOn: true,
		Keywords: []string{`medicare`},
		WholeWordKeywords: []string{},
		NearMissKeywords: []string{},
		NearMissFallback: false,
		Checksum: `au_medicare`,
		ChecksumRequired: false,
	},
	{
		Name: `au_acn`,
		Country: `AU`,
		Kind: `company`,
		Regex: `\b\d{3}[ \t]?\d{3}[ \t]?\d{3}\b`,
		Redaction: `[ACN_REDACTED]`,
		Type: `au_acn`,
		Label: `ACN`,
		RequiresKeyword: true,
		AlwaysOn: false,
		Keywords: []string{`acn`, `company number`, `australian company`},
		WholeWordKeywords: []string{},
		NearMissKeywords: []string{},
		NearMissFallback: false,
		Checksum: ``,
		ChecksumRequired: false,
	},
	{
		Name: `au_phone_intl`,
		Country: `AU`,
		Kind: `phone`,
		Regex: `\+61[ \t]?[2-478](?:[ \t]?\d){8}\b`,
		Redaction: `[PHONE_REDACTED]`,
		Type: `au_phone`,
		Label: `PHONE`,
		RequiresKeyword: false,
		AlwaysOn: false,
		Keywords: []string{},
		WholeWordKeywords: []string{},
		NearMissKeywords: []string{},
		NearMissFallback: false,
		Checksum: ``,
		ChecksumRequired: false,
	},
	{
		Name: `us_itin`,
		Country: `US`,
		Kind: `tax_id`,
		Regex: `\b9\d{2}-[7-9]\d-\d{4}\b`,
		Redaction: `[ITIN_REDACTED]`,
		Type: `us_itin`,
		Label: `ITIN`,
		RequiresKeyword: false,
		AlwaysOn: false,
		Keywords: []string{},
		WholeWordKeywords: []string{},
		NearMissKeywords: []string{},
		NearMissFallback: false,
		Checksum: ``,
		ChecksumRequired: false,
	},
	{
		Name: `us_passport_alpha`,
		Country: `US`,
		Kind: `passport`,
		Regex: `\b[A-Z]\d{8}\b`,
		Redaction: `[PASSPORT_REDACTED]`,
		Type: `us_passport`,
		Label: `PASSPORT`,
		RequiresKeyword: true,
		AlwaysOn: false,
		Keywords: []string{`passport`},
		WholeWordKeywords: []string{},
		NearMissKeywords: []string{},
		NearMissFallback: false,
		Checksum: ``,
		ChecksumRequired: false,
	},
	{
		Name: `uk_phone_full`,
		Country: `GB`,
		Kind: `phone`,
		Regex: `(?:\+44[ \t]?|\b0)(?:7\d{3}|\d{2,4})[ \t]?\d{3,4}[ \t]?\d{3,4}\b`,
		Redaction: `[PHONE_REDACTED]`,
		Type: `uk_phone`,
		Label: `PHONE`,
		RequiresKeyword: false,
		AlwaysOn: false,
		Keywords: []string{},
		WholeWordKeywords: []string{},
		NearMissKeywords: []string{},
		NearMissFallback: false,
		Checksum: ``,
		ChecksumRequired: false,
	},
	{
		Name: `uk_sort_code`,
		Country: `GB`,
		Kind: `bank`,
		Regex: `\b\d{2}-\d{2}-\d{2}\b`,
		Redaction: `[SORT_CODE_REDACTED]`,
		Type: `uk_sort_code`,
		Label: `SORT_CODE`,
		RequiresKeyword: true,
		AlwaysOn: false,
		Keywords: []string{`sort code`, `sort-code`, `bank`, `account`},
		WholeWordKeywords: []string{},
		NearMissKeywords: []string{},
		NearMissFallback: false,
		Checksum: ``,
		ChecksumRequired: false,
	},
	{
		Name: `uk_nino`,
		Country: `GB`,
		Kind: `national_id`,
		Regex: `\b[A-Z]{2}[ \t]?\d{2}[ \t]?\d{2}[ \t]?\d{2}[ \t]?[A-D]\b`,
		Redaction: `[NINO_REDACTED]`,
		Type: `national_id`,
		Label: `NINO`,
		RequiresKeyword: true,
		AlwaysOn: false,
		Keywords: []string{`national insurance`, `ni number`, `nino`, `ni:`, `insurance number`},
		WholeWordKeywords: []string{},
		NearMissKeywords: []string{},
		NearMissFallback: false,
		Checksum: ``,
		ChecksumRequired: false,
	},
	{
		Name: `uk_nhs`,
		Country: `GB`,
		Kind: `health_id`,
		Regex: `\b\d{3}[ \t]?\d{3}[ \t]?\d{4}\b`,
		Redaction: `[NHS_REDACTED]`,
		Type: `health_id`,
		Label: `NHS`,
		RequiresKeyword: true,
		AlwaysOn: false,
		Keywords: []string{`nhs`, `national health`, `nhs number`, `health service`},
		WholeWordKeywords: []string{},
		NearMissKeywords: []string{},
		NearMissFallback: true,
		Checksum: `uk_nhs`,
		ChecksumRequired: true,
	},
	{
		Name: `uk_postcode`,
		Country: `GB`,
		Kind: `postcode`,
		Regex: `\b[A-Z]{1,2}\d[A-Z\d]?[ \t]?\d[A-Z]{2}\b`,
		Redaction: `[UK_POSTCODE_REDACTED]`,
		Type: `postal_code`,
		Label: `UK_POSTCODE`,
		RequiresKeyword: true,
		AlwaysOn: false,
		Keywords: []string{`postcode`, `post code`, `uk`, `united kingdom`, `britain`, `england`, `scotland`, `wales`},
		WholeWordKeywords: []string{},
		NearMissKeywords: []string{},
		NearMissFallback: false,
		Checksum: ``,
		ChecksumRequired: false,
	},
	{
		Name: `de_tax_id`,
		Country: `EU`,
		Kind: `tax_id`,
		Regex: `\b\d{2}[ \t]?\d{3}[ \t]?\d{3}[ \t]?\d{3}\b`,
		Redaction: `[TAX_ID_REDACTED]`,
		Type: `de_tax_id`,
		Label: `TAX_ID`,
		RequiresKeyword: true,
		AlwaysOn: false,
		Keywords: []string{`steuer`, `tax id`, `steuernummer`, `idnr`, `steueridentifikation`},
		WholeWordKeywords: []string{},
		NearMissKeywords: []string{},
		NearMissFallback: false,
		Checksum: `de_steuer_id`,
		ChecksumRequired: false,
	},
	{
		Name: `emirates_id`,
		Country: `AE`,
		Kind: `national_id`,
		Regex: `\b784-?\d{4}-?\d{7}-?\d\b`,
		Redaction: `[EMIRATES_ID_REDACTED]`,
		Type: `emirates_id`,
		Label: `EMIRATES_ID`,
		RequiresKeyword: false,
		AlwaysOn: false,
		Keywords: []string{},
		WholeWordKeywords: []string{},
		NearMissKeywords: []string{},
		NearMissFallback: false,
		Checksum: `ae_emirates_id`,
		ChecksumRequired: false,
	},
	{
		Name: `uae_phone`,
		Country: `AE`,
		Kind: `phone`,
		Regex: `(?:\+971[ \t]?|\b0)5[0-9][ \t]?\d{3}[ \t]?\d{4}\b`,
		Redaction: `[PHONE_REDACTED]`,
		Type: `uae_phone`,
		Label: `PHONE`,
		RequiresKeyword: false,
		AlwaysOn: false,
		Keywords: []string{},
		WholeWordKeywords: []string{},
		NearMissKeywords: []string{},
		NearMissFallback: false,
		Checksum: ``,
		ChecksumRequired: false,
	},
	{
		Name: `uae_landline`,
		Country: `AE`,
		Kind: `phone`,
		Regex: `(?:\+971[ \t]?|\b0)[2-4679][ \t]?\d{3}[ \t]?\d{4}\b`,
		Redaction: `[PHONE_REDACTED]`,
		Type: `uae_landline`,
		Label: `PHONE`,
		RequiresKeyword: false,
		AlwaysOn: false,
		Keywords: []string{},
		WholeWordKeywords: []string{},
		NearMissKeywords: []string{},
		NearMissFallback: false,
		Checksum: ``,
		ChecksumRequired: false,
	},
	{
		Name: `po_box`,
		Country: `AE`,
		Kind: `postcode`,
		Regex: `\b[Pp]\.?[Oo]\.?[ \t]*[Bb]ox[ \t]+\d{3,6}\b`,
		Redaction: `[PO_BOX_REDACTED]`,
		Type: `po_box`,
		Label: `PO_BOX`,
		RequiresKeyword: false,
		AlwaysOn: false,
		Keywords: []string{},
		WholeWordKeywords: []string{},
		NearMissKeywords: []string{},
		NearMissFallback: false,
		Checksum: ``,
		ChecksumRequired: false,
	},
	{
		Name: `sa_national_id`,
		Country: `SA`,
		Kind: `national_id`,
		Regex: `\b[12]\d{9}\b`,
		Redaction: `[NATIONAL_ID_REDACTED]`,
		Type: `sa_national_id`,
		Label: `NATIONAL_ID`,
		RequiresKeyword: true,
		AlwaysOn: false,
		Keywords: []string{`national id`, `iqama`, `national identification`, `resident id`, `saudi id`},
		WholeWordKeywords: []string{},
		NearMissKeywords: []string{},
		NearMissFallback: false,
		Checksum: `sa_national_id`,
		ChecksumRequired: false,
	},
	{
		Name: `sa_phone`,
		Country: `SA`,
		Kind: `phone`,
		Regex: `(?:\+966[ \t]?|\b0)5[0-9][ \t]?\d{3}[ \t]?\d{4}\b`,
		Redaction: `[PHONE_REDACTED]`,
		Type: `sa_phone`,
		Label: `PHONE`,
		RequiresKeyword: false,
		AlwaysOn: false,
		Keywords: []string{},
		WholeWordKeywords: []string{},
		NearMissKeywords: []string{},
		NearMissFallback: false,
		Checksum: ``,
		ChecksumRequired: false,
	},
	{
		Name: `ng_nin`,
		Country: `NG`,
		Kind: `national_id`,
		Regex: `\b\d{11}\b`,
		Redaction: `[NIN_REDACTED]`,
		Type: `ng_nin`,
		Label: `NIN`,
		RequiresKeyword: true,
		AlwaysOn: false,
		Keywords: []string{`nin`, `national id`, `national identification`},
		WholeWordKeywords: []string{},
		NearMissKeywords: []string{},
		NearMissFallback: false,
		Checksum: ``,
		ChecksumRequired: false,
	},
	{
		Name: `ng_bvn`,
		Country: `NG`,
		Kind: `bank`,
		Regex: `\b\d{11}\b`,
		Redaction: `[BVN_REDACTED]`,
		Type: `ng_bvn`,
		Label: `BVN`,
		RequiresKeyword: true,
		AlwaysOn: false,
		Keywords: []string{`bvn`, `bank verification`},
		WholeWordKeywords: []string{},
		NearMissKeywords: []string{},
		NearMissFallback: false,
		Checksum: ``,
		ChecksumRequired: false,
	},
	{
		Name: `ng_phone`,
		Country: `NG`,
		Kind: `phone`,
		Regex: `(?:\+234[ \t]?|\b0)[789]0[1-9][ \t]?\d{3}[ \t]?\d{4}\b`,
		Redaction: `[PHONE_REDACTED]`,
		Type: `ng_phone`,
		Label: `PHONE`,
		RequiresKeyword: false,
		AlwaysOn: false,
		Keywords: []string{},
		WholeWordKeywords: []string{},
		NearMissKeywords: []string{},
		NearMissFallback: false,
		Checksum: ``,
		ChecksumRequired: false,
	},
	{
		Name: `in_aadhaar`,
		Country: `IN`,
		Kind: `national_id`,
		Regex: `\b\d{4}[ \t]?\d{4}[ \t]?\d{4}\b`,
		Redaction: `[AADHAAR_REDACTED]`,
		Type: `in_aadhaar`,
		Label: `AADHAAR`,
		RequiresKeyword: true,
		AlwaysOn: false,
		Keywords: []string{`aadhaar`, `aadhar`, `uid`, `unique identification`, `aadhaar number`},
		WholeWordKeywords: []string{},
		NearMissKeywords: []string{},
		NearMissFallback: true,
		Checksum: `verhoeff`,
		ChecksumRequired: true,
	},
	{
		Name: `in_pan`,
		Country: `IN`,
		Kind: `tax_id`,
		Regex: `\b[A-Z]{5}\d{4}[A-Z]\b`,
		Redaction: `[PAN_REDACTED]`,
		Type: `in_pan`,
		Label: `PAN`,
		RequiresKeyword: false,
		AlwaysOn: false,
		Keywords: []string{},
		WholeWordKeywords: []string{},
		NearMissKeywords: []string{},
		NearMissFallback: false,
		Checksum: ``,
		ChecksumRequired: false,
	},
	{
		Name: `in_phone`,
		Country: `IN`,
		Kind: `phone`,
		Regex: `(?:\+91[ \t]?|\b0|\b)[6-9]\d{4}[ \t]?\d{5}\b`,
		Redaction: `[PHONE_REDACTED]`,
		Type: `in_phone`,
		Label: `PHONE`,
		RequiresKeyword: false,
		AlwaysOn: false,
		Keywords: []string{},
		WholeWordKeywords: []string{},
		NearMissKeywords: []string{},
		NearMissFallback: false,
		Checksum: ``,
		ChecksumRequired: false,
	},
	{
		Name: `in_ifsc`,
		Country: `IN`,
		Kind: `bank`,
		Regex: `\b[A-Z]{4}0[A-Z0-9]{6}\b`,
		Redaction: `[IFSC_REDACTED]`,
		Type: `in_ifsc`,
		Label: `IFSC`,
		RequiresKeyword: false,
		AlwaysOn: false,
		Keywords: []string{},
		WholeWordKeywords: []string{},
		NearMissKeywords: []string{},
		NearMissFallback: false,
		Checksum: ``,
		ChecksumRequired: false,
	},
	{
		Name: `in_pincode`,
		Country: `IN`,
		Kind: `postcode`,
		Regex: `\b[1-9]\d{5}\b`,
		Redaction: `[PINCODE_REDACTED]`,
		Type: `in_pincode`,
		Label: `PINCODE`,
		RequiresKeyword: true,
		AlwaysOn: false,
		Keywords: []string{`pin code`, `pincode`, `postal code`, `zip`, `address`},
		WholeWordKeywords: []string{},
		NearMissKeywords: []string{},
		NearMissFallback: false,
		Checksum: ``,
		ChecksumRequired: false,
	},
	{
		Name: `jp_my_number`,
		Country: `JP`,
		Kind: `national_id`,
		Regex: `\b\d{4}[ \t]?\d{4}[ \t]?\d{4}\b`,
		Redaction: `[MY_NUMBER_REDACTED]`,
		Type: `jp_my_number`,
		Label: `MY_NUMBER`,
		RequiresKeyword: true,
		AlwaysOn: false,
		Keywords: []string{`my number`, `individual number`, `マイナンバー`},
		WholeWordKeywords: []string{},
		NearMissKeywords: []string{},
		NearMissFallback: true,
		Checksum: `jp_my_number`,
		ChecksumRequired: true,
	},
	{
		Name: `jp_phone_intl`,
		Country: `JP`,
		Kind: `phone`,
		Regex: `\+81[ \t-]?[0-9]{1,4}[ \t-]?\d{2,4}[ \t-]?\d{4}\b`,
		Redaction: `[PHONE_REDACTED]`,
		Type: `jp_phone`,
		Label: `PHONE`,
		RequiresKeyword: false,
		AlwaysOn: false,
		Keywords: []string{},
		WholeWordKeywords: []string{},
		NearMissKeywords: []string{},
		NearMissFallback: false,
		Checksum: ``,
		ChecksumRequired: false,
	},
	{
		Name: `jp_phone_national`,
		Country: `JP`,
		Kind: `phone`,
		Regex: `\b0[0-9]{1,4}[ \t-]?\d{2,4}[ \t-]?\d{4}\b`,
		Redaction: `[PHONE_REDACTED]`,
		Type: `jp_phone`,
		Label: `PHONE`,
		RequiresKeyword: true,
		AlwaysOn: false,
		Keywords: []string{`phone`, `telephone`, `tel`, `mobile`, `cell`, `fax`, `call`, `contact`, `whatsapp`, `hotline`, `landline`, `電話`, `電話番号`, `携帯`, `携帯番号`, `でんわ`, `电话`, `手机`, `手機`, `전화`, `휴대`, `휴대폰`, `연락처`},
		WholeWordKeywords: []string{},
		NearMissKeywords: []string{},
		NearMissFallback: false,
		Checksum: ``,
		ChecksumRequired: false,
	},
	{
		Name: `cn_resident_id`,
		Country: `CN`,
		Kind: `national_id`,
		Regex: `\b\d{6}(?:19|20)\d{2}(?:0[1-9]|1[0-2])(?:0[1-9]|[12]\d|3[01])\d{3}[0-9Xx]\b`,
		Redaction: `[RESIDENT_ID_REDACTED]`,
		Type: `cn_resident_id`,
		Label: `RESIDENT_ID`,
		RequiresKeyword: true,
		AlwaysOn: false,
		Keywords: []string{`resident id`, `resident identity`, `identity card`, `id card`, `national id`, `id number`, `id no`, `id:`, `id =`, `identity number`, `hukou`, `身份证`, `身份證`, `居民身份证`, `居民身份證`},
		WholeWordKeywords: []string{},
		NearMissKeywords: []string{},
		NearMissFallback: true,
		Checksum: `cn_resident_id`,
		ChecksumRequired: true,
	},
	{
		Name: `cn_phone_intl`,
		Country: `CN`,
		Kind: `phone`,
		Regex: `\+86[ \t-]?1[3-9]\d{9}\b`,
		Redaction: `[PHONE_REDACTED]`,
		Type: `cn_phone`,
		Label: `PHONE`,
		RequiresKeyword: false,
		AlwaysOn: false,
		Keywords: []string{},
		WholeWordKeywords: []string{},
		NearMissKeywords: []string{},
		NearMissFallback: false,
		Checksum: ``,
		ChecksumRequired: false,
	},
	{
		Name: `cn_phone_national`,
		Country: `CN`,
		Kind: `phone`,
		Regex: `\b1[3-9]\d{9}\b`,
		Redaction: `[PHONE_REDACTED]`,
		Type: `cn_phone`,
		Label: `PHONE`,
		RequiresKeyword: true,
		AlwaysOn: false,
		Keywords: []string{`phone`, `telephone`, `tel`, `mobile`, `cell`, `fax`, `call`, `contact`, `whatsapp`, `hotline`, `landline`, `電話`, `電話番号`, `携帯`, `携帯番号`, `でんわ`, `电话`, `手机`, `手機`, `전화`, `휴대`, `휴대폰`, `연락처`},
		WholeWordKeywords: []string{},
		NearMissKeywords: []string{},
		NearMissFallback: false,
		Checksum: ``,
		ChecksumRequired: false,
	},
	{
		Name: `kr_rrn`,
		Country: `KR`,
		Kind: `national_id`,
		Regex: `\b\d{6}-?[1-4]\d{6}\b`,
		Redaction: `[RRN_REDACTED]`,
		Type: `kr_rrn`,
		Label: `RRN`,
		RequiresKeyword: true,
		AlwaysOn: false,
		Keywords: []string{`resident registration`, `resident number`, `registration number`, `rrn`, `jumin`, `juminbeonho`, `national id`, `id number`, `id no`, `id:`, `id =`, `identity number`, `주민등록번호`, `주민번호`},
		WholeWordKeywords: []string{},
		NearMissKeywords: []string{},
		NearMissFallback: false,
		Checksum: `kr_rrn`,
		ChecksumRequired: false,
	},
	{
		Name: `kr_phone_intl`,
		Country: `KR`,
		Kind: `phone`,
		Regex: `\+82[ \t-]?1[016789][ \t-]?\d{3,4}[ \t-]?\d{4}\b`,
		Redaction: `[PHONE_REDACTED]`,
		Type: `kr_phone`,
		Label: `PHONE`,
		RequiresKeyword: false,
		AlwaysOn: false,
		Keywords: []string{},
		WholeWordKeywords: []string{},
		NearMissKeywords: []string{},
		NearMissFallback: false,
		Checksum: ``,
		ChecksumRequired: false,
	},
	{
		Name: `kr_phone_national`,
		Country: `KR`,
		Kind: `phone`,
		Regex: `\b01[016789][ \t-]?\d{3,4}[ \t-]?\d{4}\b`,
		Redaction: `[PHONE_REDACTED]`,
		Type: `kr_phone`,
		Label: `PHONE`,
		RequiresKeyword: true,
		AlwaysOn: false,
		Keywords: []string{`phone`, `telephone`, `tel`, `mobile`, `cell`, `fax`, `call`, `contact`, `whatsapp`, `hotline`, `landline`, `電話`, `電話番号`, `携帯`, `携帯番号`, `でんわ`, `电话`, `手机`, `手機`, `전화`, `휴대`, `휴대폰`, `연락처`},
		WholeWordKeywords: []string{},
		NearMissKeywords: []string{},
		NearMissFallback: false,
		Checksum: ``,
		ChecksumRequired: false,
	},
	{
		Name: `br_cpf`,
		Country: `BR`,
		Kind: `national_id`,
		Regex: `\b\d{3}\.?\d{3}\.?\d{3}-?\d{2}\b`,
		Redaction: `[CPF_REDACTED]`,
		Type: `br_cpf`,
		Label: `CPF`,
		RequiresKeyword: false,
		AlwaysOn: false,
		Keywords: []string{},
		WholeWordKeywords: []string{},
		NearMissKeywords: []string{`cpf`, `cadastro de pessoas`, `receita federal`},
		NearMissFallback: true,
		Checksum: `br_cpf`,
		ChecksumRequired: true,
	},
	{
		Name: `br_cnpj`,
		Country: `BR`,
		Kind: `company`,
		Regex: `\b\d{2}\.?\d{3}\.?\d{3}\/?\d{4}-?\d{2}\b`,
		Redaction: `[CNPJ_REDACTED]`,
		Type: `br_cnpj`,
		Label: `CNPJ`,
		RequiresKeyword: false,
		AlwaysOn: false,
		Keywords: []string{},
		WholeWordKeywords: []string{},
		NearMissKeywords: []string{},
		NearMissFallback: false,
		Checksum: `br_cnpj`,
		ChecksumRequired: true,
	},
	{
		Name: `ca_sin`,
		Country: `CA`,
		Kind: `national_id`,
		Regex: `\b\d{3}[- \t]\d{3}[- \t]\d{3}\b`,
		Redaction: `[SIN_REDACTED]`,
		Type: `ca_sin`,
		Label: `SIN`,
		RequiresKeyword: false,
		AlwaysOn: false,
		Keywords: []string{`sin`, `social insurance`, `canada revenue`, `cra`, `employment insurance`},
		WholeWordKeywords: []string{},
		NearMissKeywords: []string{},
		NearMissFallback: false,
		Checksum: `ca_sin`,
		ChecksumRequired: false,
	},
	{
		Name: `ca_phone`,
		Country: `CA`,
		Kind: `phone`,
		Regex: `\b(\+?1[-. \t]?)?\(?\d{3}\)?[-. \t]\d{3}[-. \t]\d{4}\b`,
		Redaction: `[CA_PHONE_REDACTED]`,
		Type: `phone`,
		Label: `CA_PHONE`,
		RequiresKeyword: false,
		AlwaysOn: false,
		Keywords: []string{`phone`, `mobile`, `cell`, `tel`},
		WholeWordKeywords: []string{},
		NearMissKeywords: []string{},
		NearMissFallback: false,
		Checksum: ``,
		ChecksumRequired: false,
	},
	{
		Name: `ca_postal_code`,
		Country: `CA`,
		Kind: `postcode`,
		Regex: `\b[A-Za-z]\d[A-Za-z][ \t-]?\d[A-Za-z]\d\b`,
		Redaction: `[CA_POSTAL_REDACTED]`,
		Type: `postal_code`,
		Label: `CA_POSTAL`,
		RequiresKeyword: false,
		AlwaysOn: false,
		Keywords: []string{`postal`, `zip`, `post code`, `mailing`},
		WholeWordKeywords: []string{},
		NearMissKeywords: []string{},
		NearMissFallback: false,
		Checksum: ``,
		ChecksumRequired: false,
	},
	{
		Name: `ca_passport`,
		Country: `CA`,
		Kind: `passport`,
		Regex: `\b[A-Za-z]{2}\d{6}\b`,
		Redaction: `[CA_PASSPORT_REDACTED]`,
		Type: `passport`,
		Label: `CA_PASSPORT`,
		RequiresKeyword: true,
		AlwaysOn: false,
		Keywords: []string{`passport`, `travel document`, `citizenship`},
		WholeWordKeywords: []string{},
		NearMissKeywords: []string{},
		NearMissFallback: false,
		Checksum: ``,
		ChecksumRequired: false,
	},
	{
		Name: `za_id_number`,
		Country: `ZA`,
		Kind: `national_id`,
		Regex: `\b(\d{2})(0[1-9]|1[0-2])(0[1-9]|[12]\d|3[01])(\d{4})(0|1)(\d{2})\b`,
		Redaction: `[ZA_ID_REDACTED]`,
		Type: `za_id_number`,
		Label: `ZA_ID`,
		RequiresKeyword: false,
		AlwaysOn: false,
		Keywords: []string{},
		WholeWordKeywords: []string{},
		NearMissKeywords: []string{`sa id`, `rsa id`, `south african id`, `suid-afrikaanse id`, `id no`, `id-nommer`, `home affairs`},
		NearMissFallback: true,
		Checksum: `za_id`,
		ChecksumRequired: true,
	},
	{
		Name: `za_phone`,
		Country: `ZA`,
		Kind: `phone`,
		Regex: `(?:\+27[ \t]?|\b0)[6-8]\d[ \t]?\d{3}[ \t]?\d{4}\b`,
		Redaction: `[PHONE_REDACTED]`,
		Type: `za_phone`,
		Label: `PHONE`,
		RequiresKeyword: false,
		AlwaysOn: false,
		Keywords: []string{},
		WholeWordKeywords: []string{},
		NearMissKeywords: []string{},
		NearMissFallback: false,
		Checksum: ``,
		ChecksumRequired: false,
	},
	{
		Name: `gh_ghana_card`,
		Country: `GH`,
		Kind: `national_id`,
		Regex: `\b[A-Z]{3}-\d{8,9}-[0-9A-Z]\b`,
		Redaction: `[GHANA_CARD_REDACTED]`,
		Type: `gh_ghana_card`,
		Label: `GHANA_CARD`,
		RequiresKeyword: true,
		AlwaysOn: false,
		Keywords: []string{`ghana card`, `ghanacard`, `ghana revenue`, `nia pin`, `personal id number`, `gra tin`},
		WholeWordKeywords: []string{},
		NearMissKeywords: []string{},
		NearMissFallback: false,
		Checksum: ``,
		ChecksumRequired: false,
	},
	{
		Name: `it_codice_fiscale`,
		Country: `IT`,
		Kind: `tax_id`,
		Regex: `\b[A-Z]{6}\d{2}[ABCDEHLMPRST]\d{2}[A-Z]\d{3}[A-Z]\b`,
		Redaction: `[CODICE_FISCALE_REDACTED]`,
		Type: `it_codice_fiscale`,
		Label: `CODICE_FISCALE`,
		RequiresKeyword: true,
		AlwaysOn: false,
		Keywords: []string{`codice fiscale`, `cod. fisc`, `cod.fisc`, `c.f.`, `anagrafe tributaria`, `tessera sanitaria`},
		WholeWordKeywords: []string{},
		NearMissKeywords: []string{},
		NearMissFallback: true,
		Checksum: `it_codice_fiscale`,
		ChecksumRequired: true,
	},
	{
		Name: `ke_kra_pin`,
		Country: `KE`,
		Kind: `tax_id`,
		Regex: `\b[AP]\d{9}[A-Z]\b`,
		Redaction: `[KRA_PIN_REDACTED]`,
		Type: `ke_kra_pin`,
		Label: `KRA_PIN`,
		RequiresKeyword: true,
		AlwaysOn: false,
		Keywords: []string{`kra pin`, `kra`, `tax pin`, `itax`, `pin certificate`, `personal identification number`},
		WholeWordKeywords: []string{},
		NearMissKeywords: []string{},
		NearMissFallback: false,
		Checksum: ``,
		ChecksumRequired: false,
	},
	{
		Name: `mu_tan`,
		Country: `MU`,
		Kind: `tax_id`,
		Regex: `\b[123578]\d{7}\b`,
		Redaction: `[TAN_REDACTED]`,
		Type: `mu_tan`,
		Label: `TAN`,
		RequiresKeyword: true,
		AlwaysOn: false,
		Keywords: []string{`tax account number`, `mauritius revenue`, `tan `, `tan:`, `tan no`, `tan number`, `mra tan`},
		WholeWordKeywords: []string{},
		NearMissKeywords: []string{},
		NearMissFallback: false,
		Checksum: ``,
		ChecksumRequired: false,
	},
	{
		Name: `mx_rfc`,
		Country: `MX`,
		Kind: `tax_id`,
		Regex: `\b[A-Z]{4}\d{6}[A-Z0-9]{3}\b`,
		Redaction: `[RFC_REDACTED]`,
		Type: `mx_rfc`,
		Label: `RFC`,
		RequiresKeyword: true,
		AlwaysOn: false,
		Keywords: []string{`rfc`, `homoclave`, `registro federal de contribuyentes`, `contribuyentes`, `constancia de situación fiscal`},
		WholeWordKeywords: []string{},
		NearMissKeywords: []string{},
		NearMissFallback: false,
		Checksum: ``,
		ChecksumRequired: false,
	},
	{
		Name: `my_mykad`,
		Country: `MY`,
		Kind: `national_id`,
		Regex: `\b\d{6}-?\d{2}-?\d{4}\b`,
		Redaction: `[MYKAD_REDACTED]`,
		Type: `my_mykad`,
		Label: `MYKAD`,
		RequiresKeyword: true,
		AlwaysOn: false,
		Keywords: []string{`mykad`, `my kad`, `kad pengenalan`, `no. kad pengenalan`, `nric`, `ic number`, `no. ic`, `mykid`},
		WholeWordKeywords: []string{},
		NearMissKeywords: []string{},
		NearMissFallback: false,
		Checksum: ``,
		ChecksumRequired: false,
	},
	{
		Name: `pk_cnic`,
		Country: `PK`,
		Kind: `national_id`,
		Regex: `\b\d{5}-?\d{7}-?\d\b`,
		Redaction: `[CNIC_REDACTED]`,
		Type: `pk_cnic`,
		Label: `CNIC`,
		RequiresKeyword: true,
		AlwaysOn: false,
		Keywords: []string{`cnic`, `nadra`, `nic number`, `identity card number`, `شناختی کارڈ`, `شناختی`},
		WholeWordKeywords: []string{},
		NearMissKeywords: []string{},
		NearMissFallback: false,
		Checksum: ``,
		ChecksumRequired: false,
	},
	{
		Name: `sg_nric`,
		Country: `SG`,
		Kind: `national_id`,
		Regex: `\b[STFGM]\d{7}[A-Z]\b`,
		Redaction: `[NRIC_REDACTED]`,
		Type: `sg_nric`,
		Label: `NRIC`,
		RequiresKeyword: true,
		AlwaysOn: false,
		Keywords: []string{`nric`, `fin number`, `fin no`, `fin:`, `identity card`, `identification number`, `cpf`, `singpass`},
		WholeWordKeywords: []string{},
		NearMissKeywords: []string{},
		NearMissFallback: true,
		Checksum: `sg_nric`,
		ChecksumRequired: true,
	},
	{
		Name: `th_national_id`,
		Country: `TH`,
		Kind: `national_id`,
		Regex: `\b\d-?\d{4}-?\d{5}-?\d{2}-?\d\b`,
		Redaction: `[NATIONAL_ID_REDACTED]`,
		Type: `th_national_id`,
		Label: `NATIONAL_ID`,
		RequiresKeyword: true,
		AlwaysOn: false,
		Keywords: []string{`national id`, `thai id`, `เลขประจำตัวประชาชน`, `บัตรประชาชน`, `เลขบัตร`, `promptpay`},
		WholeWordKeywords: []string{},
		NearMissKeywords: []string{},
		NearMissFallback: true,
		Checksum: `th_national_id`,
		ChecksumRequired: true,
	},
	{
		Name: `id_nik`,
		Country: `ID`,
		Kind: `national_id`,
		Regex: `\b\d{16}\b`,
		Redaction: `[NIK_REDACTED]`,
		Type: `id_nik`,
		Label: `NIK`,
		RequiresKeyword: true,
		AlwaysOn: false,
		Keywords: []string{`nomor induk kependudukan`, `kartu tanda penduduk`, `dukcapil`},
		WholeWordKeywords: []string{`nik`, `e-ktp`, `ektp`, `ktp`, `npwp`},
		NearMissKeywords: []string{},
		NearMissFallback: false,
		Checksum: ``,
		ChecksumRequired: false,
	},
}

type Signal struct {
	Country           string
	Regex             string
	Flags             string
	Keywords          []string
	WholeWordKeywords []string
	Activates         string
}

// Signals is in evaluation order. Stop at the first signal a country matches.
var Signals = []Signal{
	{
		Country: `AU`,
		Regex: `\b\d{3}\s\d{3}\s\d{3}\b`,
		Flags: ``,
		Keywords: []string{`tfn`, `tax file`, `medicare`},
		WholeWordKeywords: []string{},
		Activates: `AU`,
	},
	{
		Country: `AU`,
		Regex: `\b\d{4}\s\d{5}\s\d{1}\b`,
		Flags: ``,
		Keywords: []string{},
		WholeWordKeywords: []string{},
		Activates: `AU`,
	},
	{
		Country: `AU`,
		Regex: `\b(0[2-9]|\+61)\d{8,9}\b`,
		Flags: ``,
		Keywords: []string{`au`, `australia`, `australian`},
		WholeWordKeywords: []string{},
		Activates: `AU`,
	},
	{
		Country: `GB`,
		Regex: `\b[A-Z]{2}[ \t]?\d{2}[ \t]?\d{2}[ \t]?\d{2}[ \t]?[A-D]\b`,
		Flags: `i`,
		Keywords: []string{`national insurance`, `ni number`, `nino`, `ni:`},
		WholeWordKeywords: []string{},
		Activates: `GB`,
	},
	{
		Country: `GB`,
		Regex: `\b[A-Z]{1,2}\d{1,2}[ \t]?\d[A-Z]{2}\b`,
		Flags: ``,
		Keywords: []string{`uk`, `united kingdom`, `britain`, `postcode`},
		WholeWordKeywords: []string{},
		Activates: `GB`,
	},
	{
		Country: `GB`,
		Regex: `\b(\+44|0044)\d{10}\b`,
		Flags: ``,
		Keywords: []string{`uk`, `united kingdom`, `britain`},
		WholeWordKeywords: []string{},
		Activates: `GB`,
	},
	{
		Country: `CA`,
		Regex: `\b\d{3}[- \t]\d{3}[- \t]\d{3}\b`,
		Flags: ``,
		Keywords: []string{`sin`, `social insurance`, `canada revenue`, `cra`, `employment insurance`},
		WholeWordKeywords: []string{},
		Activates: `CA`,
	},
	{
		Country: `CA`,
		Regex: `\b[A-Za-z]\d[A-Za-z][ \t]?\d[A-Za-z]\d\b`,
		Flags: ``,
		Keywords: []string{`canada`, `canadian`, `postal code`, `province`},
		WholeWordKeywords: []string{},
		Activates: `CA`,
	},
	{
		Country: `ZA`,
		Regex: `\b\d{13}\b`,
		Flags: ``,
		Keywords: []string{`id number`, `identity number`, `south africa`, `sa id`, `rsa`, `popia`, `fica`},
		WholeWordKeywords: []string{},
		Activates: `ZA`,
	},
	{
		Country: `ZA`,
		Regex: `\b(\+27|0)[6-8]\d{8}\b`,
		Flags: ``,
		Keywords: []string{`south africa`, `za`, `johannesburg`, `cape town`, `durban`, `pretoria`},
		WholeWordKeywords: []string{},
		Activates: `ZA`,
	},
	{
		Country: `DE`,
		Regex: `\b[1-9]\d{10}\b`,
		Flags: ``,
		Keywords: []string{`steuer`, `steuernummer`, `finanzamt`, `tax id`, `german`},
		WholeWordKeywords: []string{},
		Activates: `DE`,
	},
	{
		Country: `DE`,
		Regex: `\b(\+49|0049)\d{10,11}\b`,
		Flags: ``,
		Keywords: []string{`germany`, `german`, `deutschland`, `de`},
		WholeWordKeywords: []string{},
		Activates: `DE`,
	},
	{
		Country: `NG`,
		Regex: `\b\d{11}\b`,
		Flags: ``,
		Keywords: []string{`bvn`, `nin`, `bank verification`, `nigeria`, `nigerian`},
		WholeWordKeywords: []string{},
		Activates: `NG`,
	},
	{
		Country: `NG`,
		Regex: `\b(\+234|0)[7-9]\d{9}\b`,
		Flags: ``,
		Keywords: []string{`nigeria`, `nigerian`, `lagos`, `abuja`},
		WholeWordKeywords: []string{},
		Activates: `NG`,
	},
	{
		Country: `AE`,
		Regex: `\b784[- \t]\d{4}[- \t]\d{7}[- \t]\d{1}\b`,
		Flags: ``,
		Keywords: []string{},
		WholeWordKeywords: []string{},
		Activates: `AE`,
	},
	{
		Country: `AE`,
		Regex: `\b(\+971|00971)\d{9}\b`,
		Flags: ``,
		Keywords: []string{`uae`, `emirates`, `dubai`, `abu dhabi`},
		WholeWordKeywords: []string{},
		Activates: `AE`,
	},
	{
		Country: `IN`,
		Regex: `\b[A-Z]{5}\d{4}[A-Z]{1}\b`,
		Flags: ``,
		Keywords: []string{},
		WholeWordKeywords: []string{},
		Activates: `IN`,
	},
	{
		Country: `IN`,
		Regex: `\b\d{4}\s\d{4}\s\d{4}\b`,
		Flags: ``,
		Keywords: []string{`aadhaar`, `aadhar`, `india`, `indian`},
		WholeWordKeywords: []string{},
		Activates: `IN`,
	},
	{
		Country: `SA`,
		Regex: `\b1\d{9}\b`,
		Flags: ``,
		Keywords: []string{`saudi`, `ksa`, `riyadh`, `national id`, `iqama`},
		WholeWordKeywords: []string{},
		Activates: `SA`,
	},
	{
		Country: `SA`,
		Regex: `\b(\+966|00966)\d{9}\b`,
		Flags: ``,
		Keywords: []string{`saudi`, `ksa`, `riyadh`},
		WholeWordKeywords: []string{},
		Activates: `SA`,
	},
	{
		Country: `BR`,
		Regex: `\b\d{3}\.\d{3}\.\d{3}-\d{2}\b`,
		Flags: ``,
		Keywords: []string{`cpf`, `brazil`, `brasil`, `brazilian`},
		WholeWordKeywords: []string{},
		Activates: `BR`,
	},
	{
		Country: `BR`,
		Regex: `\b(\+55|0055)\d{11}\b`,
		Flags: ``,
		Keywords: []string{`brazil`, `brasil`},
		WholeWordKeywords: []string{},
		Activates: `BR`,
	},
	{
		Country: `JP`,
		Regex: `\b\d{4}[ \t]?\d{4}[ \t]?\d{4}\b`,
		Flags: ``,
		Keywords: []string{`my number`, `individual number`, `マイナンバー`, `個人番号`, `japan`, `japanese`, `日本`, `tokyo`, `osaka`, `nagoya`, `yokohama`},
		WholeWordKeywords: []string{},
		Activates: `JP`,
	},
	{
		Country: `JP`,
		Regex: `\b(\+81|0081)[ \t]?\d{1,4}[ \t-]?\d{2,4}[ \t-]?\d{4}\b`,
		Flags: ``,
		Keywords: []string{`japan`, `japanese`, `日本`, `tokyo`, `osaka`},
		WholeWordKeywords: []string{},
		Activates: `JP`,
	},
	{
		Country: `CN`,
		Regex: `\b\d{17}[0-9Xx]\b`,
		Flags: ``,
		Keywords: []string{`resident id`, `resident identity`, `identity card`, `id card`, `身份证`, `身份證`, `居民身份证`, `china`, `chinese`, `prc`, `beijing`, `shanghai`, `shenzhen`, `guangzhou`},
		WholeWordKeywords: []string{},
		Activates: `CN`,
	},
	{
		Country: `CN`,
		Regex: `\b(\+86|0086)[ \t]?1[3-9]\d{9}\b`,
		Flags: ``,
		Keywords: []string{`china`, `chinese`, `prc`, `beijing`, `shanghai`, `shenzhen`, `guangzhou`},
		WholeWordKeywords: []string{},
		Activates: `CN`,
	},
	{
		Country: `KR`,
		Regex: `\b\d{6}-?[1-8]\d{6}\b`,
		Flags: ``,
		Keywords: []string{`resident registration`, `resident number`, `rrn`, `jumin`, `주민등록번호`, `주민번호`, `korea`, `korean`, `seoul`, `busan`, `incheon`},
		WholeWordKeywords: []string{},
		Activates: `KR`,
	},
	{
		Country: `KR`,
		Regex: `\b(\+82|0082)[ \t]?1[016789][ \t-]?\d{3,4}[ \t-]?\d{4}\b`,
		Flags: ``,
		Keywords: []string{`korea`, `korean`, `seoul`, `busan`, `incheon`},
		WholeWordKeywords: []string{},
		Activates: `KR`,
	},
	{
		Country: `GH`,
		Regex: `\b[A-Z]{3}-\d{8,9}-[0-9A-Z]\b`,
		Flags: ``,
		Keywords: []string{`ghana card`, `ghanacard`, `ghana`, `accra`, `kumasi`, `nia pin`, `gra tin`},
		WholeWordKeywords: []string{},
		Activates: `GH`,
	},
	{
		Country: `GH`,
		Regex: `\b(\+233|00233)[ \t]?\d{9}\b`,
		Flags: ``,
		Keywords: []string{`ghana`, `ghanaian`, `accra`, `kumasi`, `tema`},
		WholeWordKeywords: []string{},
		Activates: `GH`,
	},
	{
		Country: `IT`,
		Regex: `\b[A-Z]{6}\d{2}[ABCDEHLMPRST]\d{2}[A-Z]\d{3}[A-Z]\b`,
		Flags: ``,
		Keywords: []string{`codice fiscale`, `cod. fisc`, `c.f.`, `anagrafe tributaria`, `italy`, `italia`, `italian`, `italiana`, `roma`, `milano`, `napoli`, `torino`},
		WholeWordKeywords: []string{},
		Activates: `IT`,
	},
	{
		Country: `IT`,
		Regex: `\b(\+39|0039)[ \t]?\d{9,11}\b`,
		Flags: ``,
		Keywords: []string{`italy`, `italia`, `italian`, `italiana`, `roma`, `milano`, `napoli`, `torino`},
		WholeWordKeywords: []string{},
		Activates: `IT`,
	},
	{
		Country: `KE`,
		Regex: `\b[AP]\d{9}[A-Z]\b`,
		Flags: ``,
		Keywords: []string{`kra`, `itax`, `tax pin`, `kenya`, `kenyan`, `nairobi`, `mombasa`, `kisumu`},
		WholeWordKeywords: []string{},
		Activates: `KE`,
	},
	{
		Country: `KE`,
		Regex: `\b(\+254|00254)[ \t]?\d{9}\b`,
		Flags: ``,
		Keywords: []string{`kenya`, `kenyan`, `nairobi`, `mombasa`, `kisumu`},
		WholeWordKeywords: []string{},
		Activates: `KE`,
	},
	{
		Country: `MU`,
		Regex: `\b[123578]\d{7}\b`,
		Flags: ``,
		Keywords: []string{`mauritius`, `mauritian`, `port louis`, `mauritius revenue`, `mra tan`},
		WholeWordKeywords: []string{},
		Activates: `MU`,
	},
	{
		Country: `MU`,
		Regex: `\b(\+230|00230)[ \t]?\d{7,8}\b`,
		Flags: ``,
		Keywords: []string{`mauritius`, `mauritian`, `port louis`},
		WholeWordKeywords: []string{},
		Activates: `MU`,
	},
	{
		Country: `MX`,
		Regex: `\b[A-Z]{4}\d{6}[A-Z0-9]{3}\b`,
		Flags: ``,
		Keywords: []string{`rfc`, `homoclave`, `contribuyentes`, `mexico`, `méxico`, `mexican`, `mexicano`, `cdmx`, `guadalajara`, `monterrey`},
		WholeWordKeywords: []string{},
		Activates: `MX`,
	},
	{
		Country: `MX`,
		Regex: `\b(\+52|0052)[ \t]?\d{10}\b`,
		Flags: ``,
		Keywords: []string{`mexico`, `méxico`, `mexican`, `mexicano`, `cdmx`, `guadalajara`, `monterrey`},
		WholeWordKeywords: []string{},
		Activates: `MX`,
	},
	{
		Country: `MY`,
		Regex: `\b\d{6}-\d{2}-\d{4}\b`,
		Flags: ``,
		Keywords: []string{`mykad`, `kad pengenalan`, `nric`, `malaysia`, `malaysian`, `kuala lumpur`, `johor`, `penang`, `putrajaya`, `selangor`},
		WholeWordKeywords: []string{},
		Activates: `MY`,
	},
	{
		Country: `MY`,
		Regex: `\b\d{12}\b`,
		Flags: ``,
		Keywords: []string{`mykad`, `my kad`, `kad pengenalan`, `mykid`},
		WholeWordKeywords: []string{},
		Activates: `MY`,
	},
	{
		Country: `MY`,
		Regex: `\b(\+60|0060)[ \t]?\d{9,10}\b`,
		Flags: ``,
		Keywords: []string{`malaysia`, `malaysian`, `kuala lumpur`, `johor`, `penang`},
		WholeWordKeywords: []string{},
		Activates: `MY`,
	},
	{
		Country: `PK`,
		Regex: `\b\d{5}-\d{7}-\d\b`,
		Flags: ``,
		Keywords: []string{`cnic`, `nadra`, `pakistan`, `pakistani`, `karachi`, `lahore`, `islamabad`, `rawalpindi`, `شناختی`},
		WholeWordKeywords: []string{},
		Activates: `PK`,
	},
	{
		Country: `PK`,
		Regex: `\b\d{13}\b`,
		Flags: ``,
		Keywords: []string{`cnic`, `nadra`, `شناختی`},
		WholeWordKeywords: []string{},
		Activates: `PK`,
	},
	{
		Country: `PK`,
		Regex: `\b(\+92|0092)[ \t]?3\d{9}\b`,
		Flags: ``,
		Keywords: []string{`pakistan`, `pakistani`, `karachi`, `lahore`, `islamabad`},
		WholeWordKeywords: []string{},
		Activates: `PK`,
	},
	{
		Country: `SG`,
		Regex: `\b[STFGM]\d{7}[A-Z]\b`,
		Flags: ``,
		Keywords: []string{`nric`, `singpass`, `cpf`, `iras`, `singapore`, `singaporean`},
		WholeWordKeywords: []string{},
		Activates: `SG`,
	},
	{
		Country: `SG`,
		Regex: `\b(\+65|0065)[ \t]?[689]\d{3}[ \t]?\d{4}\b`,
		Flags: ``,
		Keywords: []string{`singapore`, `singaporean`},
		WholeWordKeywords: []string{},
		Activates: `SG`,
	},
	{
		Country: `TH`,
		Regex: `\b\d-\d{4}-\d{5}-\d{2}-\d\b`,
		Flags: ``,
		Keywords: []string{`national id`, `thai`, `thailand`, `เลขประจำตัวประชาชน`, `บัตรประชาชน`, `bangkok`, `promptpay`},
		WholeWordKeywords: []string{},
		Activates: `TH`,
	},
	{
		Country: `TH`,
		Regex: `\b\d{13}\b`,
		Flags: ``,
		Keywords: []string{`thai id`, `thailand`, `เลขประจำตัวประชาชน`, `บัตรประชาชน`, `promptpay`},
		WholeWordKeywords: []string{},
		Activates: `TH`,
	},
	{
		Country: `TH`,
		Regex: `\b(\+66|0066)[ \t]?\d{9}\b`,
		Flags: ``,
		Keywords: []string{`thailand`, `thai`, `bangkok`, `phuket`, `chiang mai`},
		WholeWordKeywords: []string{},
		Activates: `TH`,
	},
	{
		Country: `ID`,
		Regex: `\b\d{16}\b`,
		Flags: ``,
		Keywords: []string{`nomor induk kependudukan`, `kartu tanda penduduk`, `dukcapil`},
		WholeWordKeywords: []string{`nik`, `e-ktp`, `ektp`, `ktp`, `npwp`},
		Activates: `ID`,
	},
	{
		Country: `ID`,
		Regex: `\b(\+62|0062)[ \t]?\d{9,12}\b`,
		Flags: ``,
		Keywords: []string{`indonesia`, `indonesian`, `jakarta`, `surabaya`, `bandung`, `medan`, `bali`},
		WholeWordKeywords: []string{},
		Activates: `ID`,
	},
}
